### ISSUE TITLE
[Web] Plugins not loaded on frontend

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#431] opened 2020-08-12 14:00 UTC
**How to reproduce:** run the latest version of CodeCompass (`Ericsson/master`) on Ubuntu 20.04.
(The bug is not present on Ubuntu 18.04.)

**Malfunctions:**
- search toolbar is not shown on top;
- user guide tab is not shown on main area;
- right click functions basically do not work at all (menus are not shown).

There are no error messages on the JavaScript error log (in the browser), no failed HTTP request and no error on the server log (even with debug level logging).

**The bug can be tested here:**
http://codecompass.net:8020/

**Screenshots:**
![image](https://user-images.githubusercontent.com/7405458/90024198-e3113080-dcb4-11ea-85b3-588a46a3138f.png)

![image](https://user-images.githubusercontent.com/7405458/90024118-cd037000-dcb4-11ea-9c48-9a1d2122b2b0.png)

**Comment by mcserep** [comment] 2020-08-12 14:01
The bug is not present with this version of CodeCompass:
*Docker runtime image (#409)* 0f3ab694c2cd1155387fb57f7c2d2babe70ef24f

**Comment by whisperity** [comment] 2020-08-12 16:04
Findings so far: it seems none of the plugin-specific JSes are compiled into the `bundle.js` target. When trying the `bundle.js.uncompressed.js` from a live server, grepping any real CodeCompass specific thing, such as `reparse` or `Blame` or `Get AST HTML` or `Text search` (some string literals from the program), there are **0** findings in the output.

By the looks of it, the builder packages the CodeCompass UI core (explains why InfoTree, File manager, the code viewer and such still work, as they're part of the core...), but don't copy in the plugins, and as such, they cannot get loaded by the browser.

**Comment by whisperity** [comment] 2020-08-14 11:09
I have created a brand new build on Ubuntu 18.04 and I got the bug...

**Comment by whisperity** [comment] 2020-08-14 11:21
When I do `make install` and the build script gets to the part where `/home/w/Work/CodeCompass/Install-C10/share/codecompass/webgui/scripts/codecompass.profile.js` is processed, the file's contents are as follows:

~~~{.js}
        'codecompass/bundle': {
            include: [
                'codecompass/codecompass',
                'codecompass/view/codeBites', 'codecompass/view/diagram', 'codecompass/view/fileManager', 'codecompass/view/header', 'codecompass/view/infoPage', 'codecompass/view/infoTree', 'codecompass/view/infobox', 'codecompass/view/text' // CMake will insert the list of files
            ]
        },
~~~

I think the issue is that the file that is being processed by the script resides in the **install** (and not the **build**) directory, and perhaps the Dojo builder happens *earlier* than the copying of the plugin-specific JSes to the install directory.

[CMake's `file(GLOB` is notoriously "broken"](https://cmake.org/cmake/help/latest/command/file.html#glob) as it only executes the expression *when the configuration changes* (i.e. when `cmake` itself is invoked).
Instead of the current approach, I think the more working one is that instead of using GLOB expressions, plugin CMakeLists should **explicitly** register the list of JS files they are delivering. (Similarly to how `add_library` requires listing the `.cpp` files.)

(Doing that would also solve part of the issue I've detailed in #273 about `GLOB` expressions.)

@bruntib Can you take a gander at this, perhaps the fix is easy, or should we roll back #402 until @mcserep can get around reworking it?

Currently, I have found one workaround, which involves forcing CMake to regenerate the embedded list:

~~~{.sh}
make install
rm <install_directory>/share/codecompass/webgui/scripts/codecompass.profile.js
make install
~~~

This will make on the second install the profile to have the plugin-specific files present. In addition, this is confirmed by the warnings of the optimiser:

~~~
[...]
warn(205) Module not tagged as pure AMD yet it contains AMD API applications. module: codecompass/view/cppMenu
warn(205) Module not tagged as pure AMD yet it contains AMD API applications. module: codecompass/view/cppReparseFileAST
~~~

At the first build, such warnings about plugin-delivered JS files are **not** present when using a clean build.

**Comment by mcserep** [comment] 2020-08-14 12:47
@whisperity Thanks for your work on this issue.
Even if the plugin specific JS files are not properly bundled, they should still be loaded (with more HTTP requests though, like it was before #402):
https://github.com/Ericsson/CodeCompass/blob/c1e89d99bb795406bbd44713bb186498228b677c/webgui/index.html#L107

Of course this seemingly does not work, I will examine it later.

**Comment by mcserep** [comment] 2020-08-18 14:46
@whisperity You have deduced correctly the source of the issue (missing plugin JS files from the bundle), however the reason seems to be quite trivial for this after a quick check:
```cmake
# Modules
add_subdirectory(logger)
add_subdirectory(model)
add_subdirectory(parser)
add_subdirectory(scripts)
add_subdirectory(service)
add_subdirectory(util)
add_subdirectory(webgui)
add_subdirectory(webserver)
# Plugins
add_subdirectory(plugins)
```

So `plugins` is **after** the `webgui`. Is there any reason not to switch their order?

**Comment by mcserep** [comment] 2020-08-18 14:50
> Even if the plugin specific JS files are not properly bundled, they should still be loaded (with more HTTP requests though, like it was before #402):
> https://github.com/Ericsson/CodeCompass/blob/c1e89d99bb795406bbd44713bb186498228b677c/webgui/index.html#L107-L108
> 
> Of course this seemingly does not work, I will examine it later.

This does not work because of the same reason, since `add_subdirectory(webgui)` precedes `add_subdirectory(plugins)`, the JS file are copied to the `release` folder by the Dojo Build System, before the plugin specific JS files are copied to the installation directory at all.

**Comment by whisperity** [comment] 2020-08-19 13:24
This should be fixed in a more future proof way: instead of running the `GLOB` right when the `webgui` CMake is called, the whole thing should *only* be called *right before* the install target is executed.

The current solution in #445 works, but once again the core CodeCompass directories are not in alphabetical order...

**Comment by mcserep** [comment] 2020-08-19 13:39
@whisperity The `GLOB` is called during the installation process, but previously `webgui`'s installation phase preceded `plugins` installation phase. Hence the switch.

So the elegant solution would be to create a function which is executed **after** the complete installation phase. If it is not trivial, I think we shall open a new issue, because it is more like a refactoring task than a critical issue.

**Closed** 2020-08-19 13:42 UTC
Labels: Kind: Bug, Kind: Critical, Target: WebGUI
