### ISSUE TITLE
C++ parser out of range exception

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodeCompass#99] opened 2017-02-15 08:27 UTC
I tried to parse a cmake based project: https://github.com/gccxml/gccxml. 
At the end of the parse it threw an out of range exception:

```
[INFO] (387/387) Parsing /projects/gccxml/GCC_XML/GXFront/gxFront.cxx
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)
```

*Note:* I compiled this project with 16 threads.

**Comment by whisperity** [comment] 2017-03-07 12:31
The same happens with `12` threads on LLVM:

> [INFO] (117/2753) Parsing /home/whisperity/large/CodeCompass/projects/llvm/utils/TableGen/Attributes.cpp
> warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
> terminate called after throwing an instance of 'std::out_of_range'
>  what():  _Map_base::at
>Aborted (core dumped)

**Comment by bruntib** [comment] 2017-10-23 22:27
#211 fixed such an error. The error message was the same, but it happened in a module which didn't exist when this issue was created. However this fix could correct this error too, so please check if you can reproduce it.

**Comment by intjftw** [comment] 2019-10-15 09:56
I tried reproducing this error on the successor of GCCXML: [https://github.com/CastXML/CastXML](https://github.com/CastXML/CastXML)
I compiled the project on 16 threads, then parsed it on 16 threads as well, and parsed it without a problem. We have also been parsing LLVM correctly since this problem emerged. @mcserep would you take a look?

**Comment by mcserep** [comment] 2019-10-15 13:29
We have tested parallel parsing many times in the past year. Since we have never faced this issue and you could not reproduce it on the project for which the bug was reported, I think we can assume that it was fixed by @bruntib (or by other modifications). We can reopen it if someone reproduces it.

**Closed by mcserep** 2019-10-15 13:29 UTC
Labels: Kind: Bug, Kind: Critical, Status: Invalid
