### ISSUE TITLE
C++ parser says "Already parsed" for object files

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#230] opened 2018-03-06 13:53 UTC
$SUBJECT, while in reality, these files are never meant to be parsed.

**Comment by whisperity** [comment] 2018-04-25 07:46
This issue happens because there can be multiple link commands that use the same object as source (`file` entry in the JCDB). A heuristic should be implemented into the CPP parser's build-json understanding module which eliminates parsing of object files (for now, until we want to support reading information out of binaries? :stuck_out_tongue_winking_eye: ). Adding the link commands to the database should be done (at least when #198's feature is not turned off by the command-line) as #198 depends on it.

**Comment by mcserep** [comment] 2021-05-08 19:51
Could not reproduce this bug, so closing it.
Feel free to reopen it if the issue still persists.

**Closed by mcserep** 2021-05-08 19:51 UTC
Labels: Kind: Bug, Plugin: C++
