### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zsofiaschell** [Ericsson/CodeCompass#463] opened 2020-09-01 12:14 UTC
While clicking on the Info Tree of void SessionManagerAccess::auth_logout() (CodeCompass/webserver/src/session.cpp) function and selecting This Calls, the webserver stops with a segmentation fault. In plugins/cpp/service/src/cppservice.cpp funcNodes is empty and defNode.mangledHashName is 15605428051579401785, which cannot be found in the CppAstNode table.

**Comment by mcserep** [comment] 2020-10-15 13:20
Previously I could not reproduce this bug on https://codecompass.net.

Now I tried it on my developer notebook with the current master branch and had no issue again. It is also true that by merging in #429,  *mangledHashNames* were eliminated in the codebase in favor of usr, thus this issue is most likely fixed even if it existed at some point.

Can you try it out @zsofiaschell on your own computer? Make a clean build and install of CodeCompass to be on the safe side.
If you face no crash this time, I think we can close this issue.

**Closed** 2020-10-27 20:31 UTC
Labels: Kind: Bug, Plugin: C++, Status: Invalid
