### ISSUE TITLE
Show files from the point where the user left it the last time

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#389] opened 2020-05-18 08:05 UTC
Now when switching between parsed files in the web client, the view always displays the current file from its very beginning. Maybe it would be nice to store where the user were in the file when they switched to another one. It could be useful e.g. when switching between associated files like a .h and a .cpp file.

**Comment by mcserep** [comment] 2020-05-18 13:54
Isn't this a duplicate of #382 ?

**Closed** 2020-05-18 13:55 UTC
Labels: Discussion, Kind: Enhancement, Status: Duplicate, Target: Visualisation

**Comment by intjftw** [comment] 2020-05-19 11:11
I meant that if the user opened any file in a session, it would be useful if, when switching back to the file (**not** using the "go back" button in the browser), the file would be opened where the user left it.
